### ISSUE TITLE
`vagrant up examples` command hangs, at least with the described combination of software

### ISSUE THREAD

**Issue by jafingerhut** [p4tc-dev/p4tc-tutorial-pub#2]
Host machine that I tried these steps on:

+ 2019 Intel-based MacBook Pro, 64 GB of RAM
+ macOS 12.7.5
+ VirtualBox 7.0.18 (latest available as of date this issue was created)
+ vagrant 2.4.1 (latest available as of date this issue was created)

Steps I tried that failed:
```
git clone https://github.com/p4tc-dev/p4tc-tutorial-pub
cd p4tc-tutorial-pub
cd vm
vagrant plugin install vagrant-disksize
vagrant plugin install vagrant-reload
vagrant plugin install vagrant-vbguest
vagrant plugin install vagrant-scp
vagrant up examples
```

When I instead tried:
+ removing all of the plugins
+ editing my local copy of vm/Vagrantfile to remove the lines that check for the vagrant-disksize plugin

then the following steps seemed to create a working VM:
```
git clone https://github.com/p4tc-dev/p4tc-tutorial-pub
cd p4tc-tutorial-pub
cd vm
# edit Vagrantfile as mentioned above
vagrant plugin install vagrant-reload
vagrant up examples
```
then the installation seemed to proceed as expected.  At least, it did not hang in the way that the steps above did for me, and with the resulting VM I was able to log in to the VM.

**Comment by vbnogueira** [comment]
We reproduced it in Linux and it seems to be caused by an update in the `vagrant-vbguest` plugin
However, just removing `vagrant-vbguest` and leaving the other plugins worked here (Ubuntu)
We have somebody testing in windows now also before we submit the pull request to fix this

**Comment by jafingerhut** [comment]
I have now tested with the currently published instructions, with no changes to the latest files in this repo, _except_ that I made sure that the plugin `vagrant-vbguest` was not installed, but the other 3 plugins were installed.  `vagrant up examples` successfully built a VM that I could log into, and the user `vagrant`'s home directory had many files in it, including a clone of the repo p4tc-examples-pub

**Comment by vbnogueira** [comment]
> I have now tested with the currently published instructions, with no changes to the latest files in this repo, _except_ that I made sure that the plugin `vagrant-vbguest` was not installed, but the other 3 plugins were installed. `vagrant up examples` successfully built a VM that I could log into, and the user `vagrant`'s home directory had many files in it, including a clone of the repo p4tc-examples-pub

Great, thank you for testing
Opened a pull request to solve the issue (https://github.com/p4tc-dev/p4tc-tutorial-pub/pull/5)
