### ISSUE TITLE
Recommend changing README to log in as user vagrant, not p4tc

### ISSUE THREAD

**Issue by jafingerhut** [p4tc-dev/p4tc-tutorial-pub#3]
This line of the README recommends logging in as user `p4tc` to the VM:
```bash
ssh -p 2222 p4tc@127.0.0.1
# password: p4tc
```
However, that user account has no files in its home directory, and the files in /home/vagrant are not readable as user `p4tc` without using `sudo`, so it seems kind of useless to log in as that user.  I would recommend changing the above lines of the README to say this instead:
```bash
ssh -p 2222 vagrant@127.0.0.1
# password: vagrant
```

**Comment by vbnogueira** [comment]
@jafingerhut thank you for the catch
We merged a PR (https://github.com/p4tc-dev/p4tc-tutorial-pub/pull/4) implemeting your suggestion

**Comment by jafingerhut** [comment]
Closing as completed.  Thanks.
